name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/.version'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate checksum
        run: ./.github/workflows/Get-Checksum.ps1
        shell: pwsh

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["src/tools.chocolateyinstall.ps1"]'
        env:
          CHECKSUM: "${{ env.checksum }}"

      - name: choco pack
        run: |
          choco pack --version $env:VERSION ./src/podman.nuspec
        env:
          VERSION: "${{ env.version }}"
        shell: pwsh

      - name: choco push
        run: |
          choco apikey --key $env:API_KEY --source "https://push.chocolatey.org/"

          choco push --source "https://push.chocolatey.org/" --version $env:VERSION
        env:
          API_KEY: ${{ secrets.CHOCO_API_KEY }}
          VERSION: "${{ env.version }}"
        shell: pwsh
